### ISSUE TITLE
Only python?

### ISSUE THREAD

**Issue by ice1000** [Phosphorus15/ScriptIt#1]
Any possibility for reusing the common logic and provide optional submodules which makes use of concrete scripting language?

Have you ever heard about Java's builtin scripting engine?

**Comment by ice1000** [comment]
`import javax.script`

**Comment by Phosphorus15** [comment]
Yep, actually the implementations are finished all by `java.script` support

As you could see, the default implementation of plugin object uses `javax.script.Bindings` for managing scopes of each plugin

```java
public class JavaxScriptPlugin extends ScriptPlugin {

    private Bindings currentBindings;
```

And it is surely available to add sub-modules on to it, just extends the `ScriptPluginManager` (which is an abstract class) and implements the methods following the java docs written

While this repo is not mature and is somewhat for personal use, not SPI system was currently written, but I'm sure to do something about it later

thx for your suggestions 👌

**Comment by Phosphorus15** [comment]
btw, I'm not sure if it is appropriate for just designing a event system
the javascript plugin might seems like this now
```javascript
plugin("Test Js Plugin")
jimport("java.util.Date")

function onLoad(event) {
    print("plugin name : " + self.getName())
    print("plugin id : " + self.getId())
    print(self == event.get("plugin").get())
    print("The exact time now is " + new Date())
}

subscribe(Events.Load, onLoad) 
```

of course you could customize your own event type (which has been somewhat complex up to now)

but are there some other system I should have built for a plugin framework ? (I mean, something except event system)

many thx ❤️

**Comment by Phosphorus15** [comment]
well, I've updated a `python` sample just now, which is for basic exhibition under current progress.

the **same plugin** could be created using `javascript`, as well. If you would like to. (with a little changes on java codes)

here are links to the samples

* [Java Source File](https://github.com/Phosphorus15/ScriptIt/blob/master/src/test/java/naive/editor/EditorTest.java)

* [Python Plugin Source File](https://github.com/Phosphorus15/ScriptIt/blob/master/src/test/resources/dtest.py)

☺️

**Comment by ice1000** [comment]
> While this repo is not mature and is somewhat for personal use

Then you happy jiu OK.
